//! Le asigno a cada letra su igual en orden QWERTY y un nodo en el DOM
export const key1 = document.getElementById("Q")
export const key2 = document.getElementById("W")
export const key3 = document.getElementById("E")
export const key4 = document.getElementById("R")
export const key5 = document.getElementById("T")
export const key6 = document.getElementById("Y")
export const key7 = document.getElementById("U")
export const key8 = document.getElementById("I")
export const key9 = document.getElementById("O")
export const key10 = document.getElementById("P")
export const key11 = document.getElementById("A")
export const key12 = document.getElementById("S")
export const key13 = document.getElementById("D")
export const key14 = document.getElementById("F")
export const key15 = document.getElementById("G")
export const key16 = document.getElementById("H")
export const key17 = document.getElementById("J")
export const key18 = document.getElementById("K")
export const key19 = document.getElementById("L")
export const key20 = document.getElementById("Z")
export const key21 = document.getElementById("X")
export const key22 = document.getElementById("C")
export const key23 = document.getElementById("V")
export const key24 = document.getElementById("B")
export const key25 = document.getElementById("N")
export const key26 = document.getElementById("M")

